### ISSUE TITLE
Notebook "5.-Docking_Analysis.ipynb" is empty

### ISSUE THREAD

**Issue by mverissi** [AngelRuizMoreno/Jupyter_Dock#2]
Hi Angel,

First, I'd like to thank you for the wonderful work of setting this up. I'm a newcomer to the field of molecular docking, and I'm currently supervising a student in a molecular docking project. It'll make both our lives much easier!

The notebook for docking analysis is empty. Is it on purpose? Could you kindly provide a copy of a working notebook for docking analysis?

Best,

Marcos

------------

Marcos Verissimo Alves
Departamento de Fisica - ICEx - Universidade Federal Fluminense
Volta Redonda, RJ - Brazil

**Comment by AngelRuizMoreno** [comment]
Hi Marcos. 

Thank you for your comment. 

The Analysis notebook is still empty because I am still working in the documentation of the docking protocols. The analysis notebook will be included in a future release. I'm still working on it in order to provide a general analysis that can be run after docking.

Best.

Angel

**Comment by AngelRuizMoreno** [comment]
> 

Dear Marcos,

I just did a new push containing part of the Analysis notebook. You can take a look at it and see if the current information is of your interest. New analysis will be added in future as well as the corresponding documentations (see 1. Molecular Docking for reference).

Best. 

Angel

**Comment by mverissi** [comment]
Dear Angel,

Thank you so much for the analysis notebook. I apologize for not having
answered you earlier, but this last week has been a pretty heavy one.

Best regards,

Marcos

Em qua, 24 de nov de 2021 14:27, Angel J. Ruiz Moreno <
***@***.***> escreveu:
