### ISSUE TITLE
Autodock-GPU

### ISSUE THREAD

**Issue by jixing475** [AngelRuizMoreno/Jupyter_Dock#3]
Hi, Can the Autodock-GPU be supported?

**Comment by AngelRuizMoreno** [comment]
Hi jixing475,

In theory, the AutoDock-GPU executable, like the other tools, can be set up and run directly in the notebook (Vina, Smina, LeDock). Nonetheless, I haven't tested the tool either inside or outside of Jupyter Dock. If you could generate the protocol, I would be happy to include the notebook for AutoDock-GPU.

Best wishes.
